In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup 
import matplotlib.pyplot as plt
import pyimgur
from linebot.models import *
message = 2330
url = "https://tw.stock.yahoo.com/quote/" + str(message) +"/institutional-trading"
res = requests.get(url)
soup = BeautifulSoup(res.text,"html.parser")
soup1 = soup.find_all("div",{"style":"padding:0 12px 0 0"})[4:]

date = []
foreign_inv = []
credit = []
self_employed = []
total = []
foreign_sharehold = []
for i in soup1:
    soup2 = i.find_all("div")
    date.append(soup2[1].text)
    foreign_inv.append(soup2[2].text)
    credit.append(soup2[3].text)
    self_employed.append(soup2[4].text)
    total.append(soup2[5].text)
    foreign_sharehold.append(soup2[6].text)
df = pd.DataFrame({"日期":date,"外資(張)":foreign_inv,"投信(張)":credit,"自營商(張)":self_employed,"合計(張)":total,"外資持股率(%)":foreign_sharehold})
df.index = pd.to_datetime(df["日期"])
df.index = df.index.format(formatter=lambda x: x.strftime('%Y-%m-%d'))
df.drop("日期",axis = 1,inplace=True)
int_ = ["外資(張)","投信(張)","自營商(張)","合計(張)"]
for i in int_:
    df[i] = df[i].apply(lambda x: x.replace(",","")).astype("int64")
df["外資持股率(%)"] = df["外資持股率(%)"].apply(lambda x: x.replace("%","")).astype(float)
df

            外資(張)  投信(張)  自營商(張)  合計(張)  外資持股率(%)
2023-01-05   6726    -17    -635   6074     70.88
2023-01-04  -2961    263     994  -1704     70.85
2023-01-03  -1035    229     -54   -859     70.86
2022-12-30   -166   -242     540    132     70.87
2022-12-29  -5899   -124    1168  -4854     70.87
...           ...    ...     ...    ...       ...
2022-07-12    926    -34    -534    359     71.89
2022-07-11   4851    301    -253   4899     71.89
2022-07-08   4084    244     -38   4290     71.86
2022-07-07  15562    352     775  16689     71.85
2022-07-06   1722   -256     242   1708     71.79

[129 rows x 5 columns]